### ISSUE TITLE
Problem with ffmpeg

### ISSUE THREAD

**Issue by blastentwice** [VolcanoSauce/CK3-CoA-Editor#2]
After entering the root directory to CK3, command line shows ffmpeg as not a valid command.

**Comment by blastentwice** [comment]
Also, I'm working on a family tree exporter and would love your help to implement CoA into it. If possible, please reach out to me through my discord server [discord.gg/mkfduntpfb](url). The link to my project can be found [here](https://github.com/blastentwice/CK3-Family-Tree-Exporter-To-Gramps-Fast-JSON-Version).

**Comment by VolcanoSauce** [comment]
I can't believe I forgot to add that dependency, sorry about that, I'll be fixing this in the next week. For now you can download the ffmpeg from here: https://www.ffmpeg.org/

After you finish downloading it, place the ffmpeg.exe inside "\CoAEditor\bin\Debug\netcoreapp3.*\".
Make sure to delete the CoA_Editor.cfg generated in that same location so that it can finish the initial setup appropriately, also keep in mind that it might take a few seconds (or minutes depending on your system specs) to generate the necessary files.

If you have any other problems please report them, I'd like this to work well since I use it myself as well.

**Comment by blastentwice** [comment]
Do you think it's possible to convert your program into command line? I'm actually working on a CK3 family tree exporter and would love to batch generate CoA from the CoA data in the save file.
